package bot.modules

import bot.Bot
import net.dv8tion.jda.api.JDA
import net.dv8tion.jda.api.events.GenericEvent

interface IBotModule : IModule {


	/**
	 * gets a bot the module is serving with a JDA object that matches the one given
	 * @param jda JDA object that this module serves
	 * @return bot that this module is serving with the specified JDA object
	 * @throws NullPointerException if the module is not serving any Bot with a matching JDA object
	 */
	fun getBot(jda : JDA) : Bot

	/**
	 * gets a bot the module is serving with that the given event belongs to
	 * @param event event that was generated by the bot
	 * @return bot that generated the event
	 * @throws NullPointerException if the module is not serving the bot that generated the event
	 */
	fun getBot(event: GenericEvent) : Bot

	/**
	 * gets the first bot in the list
	 * @return bot that is first in bots
	 * @throws NullPointerException if the module isn't serving any bots
	 */
	fun getBot() : Bot
}